console.log('Log')
console.error('Error')
console.info('This is an info')
console.warn('This is a warning')
console.debug('This is a debug')
const table = [{a: 1, b: 'z'},{a: 2, b: 'a'}]
console.table(table)

console.group('elementGroup')
console.log('First Element')
console.log('Second Element')
console.group('SubElementGroup')
console.log('Sub Element 1')
console.log('Sub Element 2')
console.groupEnd('SubElementGroup')
console.log('Third Element')
console.groupEnd('elementGroup')

console.count('times')
console.count('times')
console.count('times')
console.count('times')
console.count('times')
console.countReset('times')
console.count('times')
console.count('times')